cors:
  cors-origins:
    - http://localhost:3000
    - http://localhost:5173
  allowed-header: "*"
  allowed-method: "*"

spring:

  main:
    web-application-type: reactive

  application:
    name: gateway_ms

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/test_realm
          jwk-set-uri: http://host.docker.internal:8081/realms/test_realm/protocol/openid-connect/certs

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: users-service
              uri: http://social-mainpage-ms:8080
              predicates:
                - Path=/users/**
              filters:
                - RemoveRequestHeader=Cookie
            - id: ads-service
              uri: http://social-ad-ms:8080
              predicates:
                - Path=/ads/**, /categories/**
              filters:
                - RemoveRequestHeader=Cookie
            - id: chat-service
              uri: http://social-chat-ms:8080
              predicates:
                - Path=/messages/**, /conversations/**
              filters:
                - RemoveRequestHeader=Cookie
            - id: websocket-service
              uri: http://social-websocket-ms:8080
              predicates:
                - Path=/websocket-ms/**
              filters:
                - StripPrefix=0
                - WebSocketAuthFilter


server:
  port: 3020

management:
  server:
    port: 3021
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
