spring:
  application:
    name: websocketms
  kafka:
    bootstrap-servers: social-kafka-broker:9092
    consumer:
      group-id: chat-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    listener:
      missing-topics-fatal: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  server:
    port: 3021
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway