global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['social-mainpage-ms:8080', 'social-ad-ms:8080', 'social-chat-ms:8080', 'social-websocket-ms:3021', 'social-gateway-ms:3021']
