spring.application.name=chatms

user.service.url: http://social-mainpage-ms:8080

spring.datasource.url=jdbc:postgresql://social-pg:5432/social_pg_chats
spring.datasource.username=pguser
spring.datasource.password=pgpassword
spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=health,info,metrics,prometheus
