openapi: 3.0.0
info:
  title: Ad API
  version: 1.0.0

paths:
  /categories:
    get:
      summary: Get all ad categories with descriptions.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriesPage'
  /ads:
    get:
      summary: Search for ads with specified parameters.
      parameters:
         - name: userId
           in: query
           description: Filter ads by user ID.
           required: false
           schema:
             type: string
             format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdPages'
    post:
      summary: Create a new ad.
      requestBody:
        description: Title and content for new ad.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdPageRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdPage'
  /ads/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Unique ad id.
        schema:
          type: string
          format: uuid
    get:
      summary: Get ad with {id}.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdPage'
    put:
      summary: Update ad with {id}.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdPage'
    delete:
      summary: Delete ad with {id}.
      responses:
        204:
          description: No content

components:
  schemas:
    AdPages:
      type: object
      description: Object with ads.
      properties:
        ads:
          type: array
          items:
            $ref: '#/components/schemas/AdPage'
    AdPage:
      type: object
      description: Ad with ad id, title, content.
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        content:
          type: string
        category_id:
          type: string
          format: uuid
    AdPageRequest:
      type: object
      description: New ad with ad title, content.
      required:
        - title
        - content
      properties:
        title:
          type: string
          description: Ad title.
          example: "Red car with trailer ..."
        content:
          type: string
          description: Ad content.
          example: "I'd like to sell ... "
    CategoriesPage:
      type: object
      description: Object with all categories as field categories.
      properties:
        categories:
          type: array
          items:
            $ref: '#/components/schemas/CategoryPage'
    CategoryPage:
      type: object
      description: Category with id, description.
      properties:
        id:
          type: string
          format: uuid
        description:
          type: String
