openapi: 3.0.0
info:
  title: Ad API
  version: 1.0.0

paths:
  /categories:
    get:
      summary: Get all ad categories with descriptions.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriesPage'


  /ads:
    get:
      summary: Search for ads with specified parameters.
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
        - $ref: '#/components/parameters/sort'
        - name: user
          in: query
          description: Filter ads by user ID.
          required: false
          schema:
            type: string
            format: uuid
        - name: from
          in: query
          description: Filter ads later than ...
          required: false
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          description: Filter ads fresher than ...
          required: false
          schema:
            type: string
            format: date-time
        - name: users
          in: query
          description: Filter ads by users ids seperated by commas.
          required: false
          schema:
            type:
            items:
              type: string
              format:
        - name: categories
          in: query
          description: Filter ads by list of categories ids seperated by commas.
          required: false
          schema:
            type: array
            items:
              type: string
              format: uuid
        - name: keyword
          in: query
          description: Filter ads by keyword in title, content.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List of ads.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page'

    post:
      summary: Create a new ad for a logged in user.
      requestBody:
        description: Title, content, category for the new ad.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdPageRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdPage'
  /ads/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Unique ad id.
        schema:
          type: string
          format: uuid
    get:
      summary: Get ad with {id}.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdPage'
    put:
      summary: Update ad with {id}.
      requestBody:
        description: Title, content, category for updated ad.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdPageRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdPage'
    delete:
      summary: Delete ad with {id}.
      responses:
        204:
          description: No content
        '401':
          description: "Unauthorized attempt to update someone else's data."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    AdPages:
      type: object
      description: Object with ads in field ads.
      properties:
        ads:
          type: array
          items:
            $ref: '#/components/schemas/AdPage'
    AdPage:
      type: object
      description: Ad with ad id, title, content, category id, user id.
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        content:
          type: string
        category:
          type: string
          format: uuid
        user:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the entity was created
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the entity was last updated
    AdPageRequest:
      type: object
      description: New ad with ad title, content, category.
      required:
        - title
        - content
        - category
      properties:
        title:
          type: string
          description: Ad title.
          example: "Red car with trailer ..."
          minLength: 1
        content:
          type: string
          description: Ad content.
          example: "I'd like to sell ... "
          minLength: 1
        category:
          type: string
          format: uuid
          description: Category id.
    CategoriesPage:
      type: object
      description: Object with all categories as field categories.
      properties:
        categories:
          type: array
          items:
            $ref: '#/components/schemas/CategoryPage'
    CategoryPage:
      type: object
      description: Category with id, description.
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string
    ErrorResponse:
      type: object
      required:
        - status
        - message
        - timestamp
      properties:
        status:
          type: integer
          format: int32
          example: 404
        message:
          type: string
          example: Ad not found
        timestamp:
          type: string
          format: date-time
          example: 2026-03-20T14:48:00Z


    Page:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/AdPage'
        totalElements:
          type: long
        totalPages:
          type: integer
        size:
          type: integer
        number:
          type: integer
        sort:
          type: object
        first:
          type: boolean
        last:
          type: boolean
        numberOfElements:
          type: integer
        empty:
          type: boolean
  parameters:
    page:
      name: page
      in: query
      description: 0-based page number.
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
    size:
      name: size
      in: query
      description: Page size;
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
    sort:
      name: sort
      in: query
      description: Sort in format property,(asc|desc). Man options can be specified.
      required: false
      schema:
        type: array
        items:
          type: string
      style: form
      explode: true
