spring.application.name=mainpagems

spring.datasource.url=jdbc:postgresql://social-pg:5432/social_pg_users
spring.datasource.username=pguser
spring.datasource.password=pgpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info,metrics,prometheus

